//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public System.Guid Id { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public string Direccion { get; set; }
        public string RFC { get; set; }
        public string Nombre { get; set; }
        public string Logo { get; set; }
        public string Imagen { get; set; }
        public string Categoria { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.TimeSpan> HoraOpen { get; set; }
        public Nullable<System.TimeSpan> HoraClosed { get; set; }
        public string Telefono { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
