//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public System.Guid Id { get; set; }
        public string IdEmpresa { get; set; }
        public string Imagen1 { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
