//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenXPlatillos
    {
        public System.Guid Id { get; set; }
        public string IdOrden { get; set; }
        public string IdPlatillo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
